//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyTecniServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Compra
    {
        public int Id_Detalle { get; set; }
        public int Id_productos3 { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> sub_total { get; set; }
        public int Id_compra2 { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
