//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyTecniServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Venta
    {
        public int Id_Detalle_Venta { get; set; }
        public int Id_productos3 { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> sub_total { get; set; }
        public int Id_venta2 { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
